export const FETCH_LISTPOSTS = 'FETCH_LISTPOSTS';
export const FETCH_LISTPOSTS_SUCCESS = 'FETCH_LISTPOSTS_SUCCESS';
export const FETCH_LISTPOSTS_FAIL = 'FETCH_LISTPOSTS_FAIL';

export const DELETE_LISTPOSTS = 'DELETE_LISTPOSTS';
export const DELETE_LISTPOSTS_SUCCESS = 'DELETE_LISTPOSTS_SUCCESS';
export const DELETE_LISTPOSTS_FAIL = 'DELETE_LISTPOSTS_FAIL';

export const ADD_LISTPOSTS = 'ADD_LISTPOSTS';
export const ADD_LISTPOSTS_SUCCESS = 'ADD_LISTPOSTS_SUCCESS';
export const ADD_LISTPOSTS_FAIL = 'ADD_LISTPOSTS_FAIL';

export const EDIT_LISTPOSTS = 'EDIT_LISTPOSTS';
export const EDIT_LISTPOSTS_SUCCESS = 'EDIT_LISTPOSTS_SUCCESS';
export const EDIT_LISTPOSTS_FAIL = 'EDIT_LISTPOSTS_FAIL';